sudo: false
dist: trusty
language: node_js
node_js:
  - "stable"
services:
  - postgresql
before_script: 
  - npm install
  - psql -c 'CREATE DATABASE travis;' -U postgres
  - psql -c "CREATE USER emeka WITH PASSWORD 'password';" -U postgres
script:
  - npm run test
after_success:
  - npm run coverage
env:
  global:
  - export NODE_ENV=test