sudo: false
dist: trusty
language: node_js
node_js:
  - "stable"
env:
  global:
  - export NODE_ENV=test
services:
  - postgresql
before_script:
  - npm install
  - psql -c 'create database testDb;' -U postgres
script:
  - npm run test
after_success:
  - npm run coverage